services:
  - type: web
    name: how-to-knit-correctly-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
      - key: REQUIRE_EMAIL_CONFIRMATION
        value: false
